### ISSUE TITLE
Vulnerability due to recent changes in Securityconfig

### ISSUE THREAD

**Issue by idaShobs** [doctor-home/doctor_at_home_backend#11]
Fix  GET /patients endpoint vulnerability due to the recent change @atuleu to the allowed role for users that can access the endpoint. 
FindPatients should only return all patients if logged on user has the admin role. 
Due to privacy issue, if not admin, GET /patients  should return patients for current logged in user only.
However this would duplicate the functionality of /clinician/patients

A fix for the duplicate would be to add a put mapping for /clinicians/patients and then remove put mapping from patient rest controller.
 Another would be to completely  overhaul the API endpoint schema such that, patient restcontroller doesn’t exist as a stand-alone. Patients ate only to be accessed through the clinician controller.

**Comment by atuleu** [comment]
Why not just simply set the  user role on `/patients**` and set the admin role in `/patients` GET only ?

Whatever the final solution is, user should be authorized to POST/PUT on /patients, but not allowed to GET on /patients.

**Comment by idaShobs** [comment]
Totally forgot one can set the role on method basis also @atuleu 
Will do that
