### ISSUE TITLE
Do not expose password over the user API

### ISSUE THREAD

**Issue by atuleu** [doctor-home/doctor_at_home_backend#4]
Please do not expose password, even if salted and hashed to the wild thorugh the user API endpoint.

**Comment by idaShobs** [comment]
Password now hidden. However UserDTO now duplicated in SwaggerUI list of models. This is because Swagger recognizes UserDTO for \Get (Password not serialized) as one object and for \POST (Password serialized). This is just a swaggerUI parse issue.
