### ISSUE TITLE
api endpoint `/api/dah/v0/clinicians/{id}/untreatedpatients` never return match

### ISSUE THREAD

**Issue by atuleu** [doctor-home/doctor_at_home_backend#8]
the `patients` endpoint returns patient with under_observation true or false

the undreatedpatients returns nothing in all circustances.

Also, the coded criteria in CliniciansService is to return the patients which are not under observation, which is the opposite (they are treated).

**Comment by idaShobs** [comment]
Criteria now set to true and issue now automatically fixed through endpoint change
